### ISSUE TITLE
Add at90usb162 and at90usb82 support

### ISSUE THREAD

**Issue by NicoHood** [nickgammon/arduino_sketches#11]
They are equal to the 16u2 and 8u2 but have a different signature. I just dont know where to look them up. It would be nice to add them because some older/Chinese boards have them instead. So the user knows what chip he has and dont get a "not supported" error.

**Comment by nickgammon** [comment]
Done.

https://github.com/nickgammon/arduino_sketches/commit/09a778e956fe09ae0c693cff5a75c9200228308c
