### ISSUE TITLE
Add 16u2 Mega Firmware

### ISSUE THREAD

**Issue by NicoHood** [nickgammon/arduino_sketches#13]
The user should be able to select the 16u2 Firmware with another #define to also upload the 16u2 Mega firmware.

**Comment by nickgammon** [comment]
There is already a bootloader for the 16u2. The firmware for the bootloader part is identical on both boards.  For both boards you would need to go into DFU mode to load the main code (not the bootloader) as described here: http://www.gammon.com.au/forum/?id=11635&reply=2#reply2

**Comment by NicoHood** [comment]
You are totally right. I used the USB-Serial on top of the bootloader. Thatswhy it was important. Nevermind.

Thx for the merges/fixes.
