### ISSUE TITLE
Could you please add 1284P support?

### ISSUE THREAD

**Issue by liudr** [nickgammon/arduino_sketches#15]
Nick,

Thanks for your continued support on this great project! I've added my own 1284P support to your code. Since you already added 1284P support to the fixed file uploader, could you add to this code too?

There are two variants:
Standard (manicbug's mighty), and bobuino (CrossRoad's board). I am using pin defs from bobuino since it makes closer mapping to the UNO convention:

// for fast port access
#if defined (__AVR_ATmega2560__)
  // Atmega2560
  #define BB_MISO_PORT PINH
  #define BB_MOSI_PORT PORTH
  #define BB_SCK_PORT PORTG
  const byte BB_SCK_BIT = 5;
  const byte BB_MISO_BIT = 3;
  const byte BB_MOSI_BIT = 4;

#elif defined (__AVR_ATmega1284P__)
  // Atmega1284P
  #define BB_MISO_PORT PINB
  #define BB_MOSI_PORT PORTB
  #define BB_SCK_PORT PORTB
  const byte BB_SCK_BIT = 0;
  const byte BB_MISO_BIT = 2;
  const byte BB_MOSI_BIT = 3;
#else
  // Atmega328
  #define BB_MISO_PORT PIND
  #define BB_MOSI_PORT PORTD
  #define BB_SCK_PORT PORTD
  const byte BB_SCK_BIT = 3;
  const byte BB_MISO_BIT = 6;
  const byte BB_MOSI_BIT = 7;
#endif

I'm not sure how to tell different variants at compile time such as bobuino or standard. Having that in the code would be even better!

**Comment by nickgammon** [comment]
I've added support for the 1284 chip, however it is consistent with the stuff I put in the fixed-file uploader. The defines are different to what you have above. I can't easily support every board variant, I suggest you just edit the sketch and change the lines if required.

https://github.com/nickgammon/arduino_sketches/commit/bb6da2b9487f752d95e8fdb6dcb47b461f19cbef
