### ISSUE TITLE
Could you do a PR to Arduino asking for including your fantastic I2C_Anything and SPI_Anything templates in official Wire/SPI libraries?

### ISSUE THREAD

**Issue by q2dg** [nickgammon/arduino_sketches#22]
Or at least, adding them as standalone libraries to official Library Manager...it would give them more visibility, I think.
Thanks for your work.

**Comment by NicoHood** [comment]
Where do you mean? Any example?

**Comment by q2dg** [comment]
Well, this (http://www.gammon.com.au/forum/?id=10896&reply=8#reply8) and this (http://www.gammon.com.au/forum/?id=10892&reply=8#reply8)

**Comment by NicoHood** [comment]
Sounds like a cool addition!

**Comment by nickgammon** [comment]
See https://github.com/arduino/Arduino/issues/3691 and https://github.com/arduino/Arduino/issues/3692

**Comment by q2dg** [comment]
Thanks a lot!
