### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by ooanea** [nickgammon/arduino_sketches#27]
Hi,

I just replaced my arduino atmega16U2 and I need to reprogram it with bootloader then the firmware. I found interesting information here but how can I download the Atmega_Board_Programmer folder? 

Can someone help, and then I need to place in my software I believe but where.  A lot of esential basic information is missing.

thanks, Octavian

**Comment by nickgammon** [comment]
There is a "Download ZIP" button on the main page: https://github.com/nickgammon/arduino_sketches

There should be useful information here: http://www.gammon.com.au/bootloader

**Comment by ooanea** [comment]
Dear Nick,

I have managed to download, follow your instructions and brought to life my
dead Arduino. I want to thank you for sharing the long hours work I
believe. Impressive work.

Take care, Octavian,

On Wed, Oct 21, 2015 at 9:56 PM, Nick Gammon <notifications@github.com>
wrote:

> There is a "Download ZIP" button on the main page:
> https://github.com/nickgammon/arduino_sketches
>
> There should be useful information here:
> http://www.gammon.com.au/bootloader
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickgammon/arduino_sketches/issues/27#issuecomment-150007843>
> .
>



-- 


Octavian Oanea

skype: o.oanea

**Comment by nickgammon** [comment]
Glad I could help.
