### ISSUE TITLE
Support to change onboard LED pin function

### ISSUE THREAD

**Issue by csavy** [nickgammon/arduino_sketches#34]
I have a custom MEGA2560-based board that uses D10 instead of D13 for an onboard status LED.

I understand that the optiboot bootloader code flashed D13:
-at Arduino boot time (the LED blinks a few times)
-when uploading a sketch to Arduino

Please allow the user to change the pin associated with the functionality of the LED, preferably in the 
file ATmega_Board_Programmer.ino. I do not feel experienced enough to re-compile the bootloader on my own!

P.S. your code is awesome, what a life saver for custom projects - especially on MEGA2560!

**Comment by nickgammon** [comment]
The bootloaders are just hard-coded as precompiled binaries. I don't have the ability to change that in the way you request.

**Comment by csavy** [comment]
Thank you for the response. May I ask if you provide .C files I can edit and compile to institute this change?

If not, is there another way to implement his change? Perhaps links to some more tutorials like yours?

-Chris

Sent from my iPhone. Please excuse any typos.

On Jun 6, 2016, at 6:08 PM, Nick Gammon <notifications@github.com<mailto:notifications@github.com>> wrote:


The bootloaders are just hard-coded as precompiled binaries. I don't have the ability to change that in the way you request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/nickgammon/arduino_sketches/issues/34#issuecomment-224103725>, or mute the thread<https://github.com/notifications/unsubscribe/AS3oszpjkq0yM_y5DCxvatLCMRs8mksYks5qJJpPgaJpZM4IvU_G>.

________________________________

**Comment by csavy** [comment]
Much appreciated Nick, thanks again!

-Chris
