### ISSUE TITLE
Allow fuse calculator to set fuses too

### ISSUE THREAD

**Issue by xxxajk** [nickgammon/arduino_sketches#4]
While it is nice to see fuse values, it would be very handy to be able to use the same sketch to modify them.

**Comment by user0689** [comment]
Hi Nick, I get this message whenever i try to compile the Board Detector Sketch


Arduino: 1.6.1 (Mac OS X), Board: "Arduino Uno"

Build options changed, rebuilding all
sketch_mar17a.ino:53:19: fatal error: md5.h: No such file or directory
compilation terminated.
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
