### ISSUE TITLE
Trying to identify a bootloader

### ISSUE THREAD

**Issue by chupocro** [nickgammon/arduino_sketches#46]
Hi,

I have a few Arduino Nano and Pro mini boards. I backed-up the bootloaders (before erasing the flash) and then tried to identify them by searching for the first bytes: "0c 94 34 3c 0c 94 51 3c", so I found your repository.

I can see the bootloader stored in **bootloader_lilypad328.h** file has the same starting and ending bytes as bootloaders in my boards despite my boards work with 16 MHz crystal and the bootloader in **bootloader_lilypad328.h** file is for 8 MHz clock. I made a diff of these bootloaders (after converting them to binary) and the bytes are quite similar (at least in the first half of the code) but not the same.

Can you please tell if there is a source code of the bootloader stored in **bootloader_lilypad328.h** available somewhere on the net and what is its name?

Here you are the bootloader read from my Nano&Pro mini boards in Intel hex format, in case you can identify it. I would appreciate any info on that bootloader.

Regards
[bootloader_ATmega328_16MHz.zip](https://github.com/nickgammon/arduino_sketches/files/1346846/bootloader_ATmega328_16MHz.zip)

**Comment by nickgammon** [comment]
The first line of that .h file mentions where I got the hex file from:

```
/arduino-1.6.9/hardware/arduino/avr/bootloaders/atmega/ATmegaBOOT_168_atmega328_pro_8MHz.hex
```

The source file appears to be in the same directory as that.
