### ISSUE TITLE
ATmega328PB bootloader

### ISSUE THREAD

**Issue by djguy1** [nickgammon/arduino_sketches#49]
Would there be any chance of updating these bootloaders to support the new ATmega328PB microcontrollers?

**Comment by nickgammon** [comment]
Support is already there:

https://github.com/nickgammon/arduino_sketches/blob/a7ac82793f06a8474ea0c7f3ea80fcefbcc81a23/Atmega_Hex_Uploader/Signatures.h#L68

**Comment by djguy1** [comment]
Thank you for your kind reply, could you tell me why I just get the following in serial monitor?:

"Entered programming mode OK.
Signature = 0x1E 0x95 0x16 
Processor = ATmega328PB
Flash memory size = 32768 bytes.
LFuse = 0xFF 
HFuse = 0xD9 
EFuse = 0xF7 
Lock byte = 0xFF 
Clock calibration = 0x92 
No bootloader support for this device."

It works perfectly with an ATmega328P.

**Comment by nickgammon** [comment]
It would have helped to quote that error message originally. :)

The chip signature was supported but it wasn't in the list of bootloaders. That has been uploaded in this commit: https://github.com/nickgammon/arduino_sketches/commit/be4e4209c04afa470a00f671ca1a9f6242f20dc4

I am assuming that the same (Optiboot) bootloader will work with this device.

**Comment by djguy1** [comment]
My apologies. I have now updated the sketch and it now gets past that point, but when I type 'G' to program the chip I get 507 verification errors, the first of which is:

Verification error at address 7E00. Got: 0x00  Expected: 0x11, the last shown (number 100) is:
Verification error at address 7E64. Got: 0x32  Expected: 0x61 

Thank you for your kind help, it is much appreciated.

**Comment by nickgammon** [comment]
What sort of crystal are you using? Do you have decoupling capacitors on your board?

**Comment by djguy1** [comment]
16mhz, and two 22pf ceramic capacitors.

**Comment by nickgammon** [comment]
I presume the 22 pF capacitors are on the crystal legs. Do you have decoupling capacitors? Typically these are 0.1 µF and are located between +5V and Gnd near to the chip itself.

BTW 16 mhz would be very slow (16 milliherz or 16/1000000 Hz). You mean 16 MHz (16 megaherz or 16000000 Hz).

**Comment by djguy1** [comment]
Hello,

Yes, I am aware of milihertz being a small m, but I wrote that at half past two in the morning and knew you would know what I meant anyway.

I checked the decoupling capacitor on the +5v rail and found one end not soldered properly. I have resoldered this and to my amazement it now works! Thanks for all your kind help.

**Comment by nickgammon** [comment]
>  I am aware of millihertz being a small m ...

An easy mistake to make. I kept typing mS for milliseconds until someone pointed out that this meant milliSiemens. :)

Glad it's working, amazing how one capacitor changes everything.
