### ISSUE TITLE
A quick helpful update

### ISSUE THREAD

**Issue by LMDIGroup** [nickgammon/arduino_sketches#52]
I just noticed on your forum post: http://gammon.com.au/forum/?id=11638
### Producing a .hex file
Well, now in the Arduino IDE you can
>Sketch - Export Compiled Binary

Which puts the hex file right into your project directory.
Works with 1.8.5, I don't know what version it was implemented.

**Comment by nickgammon** [comment]
Thanks, I have amended that page to mention that.
