### ISSUE TITLE
Different (high fuse) boot start address

### ISSUE THREAD

**Issue by MarekBujko** [nickgammon/arduino_sketches#54]
Good day,
I try your Atmega_Board_Detector on ATmega328p, but program show me different (high fuse) boot start address compared to http://www.engbedded.com/fusecalc/
Maybe dumb question, can you explain how you recalculate in program bootloader size and startup address? Thank you in advance.

I found the answer:
Example
32 kB memory - 1 kB bootloader = 31 * 1024 = 0x7C00 (31744)
32 kB memory - 2 kB bootloader = 30 * 1024 = 0x7800 (30720)

word -> byte
0x3F00 -> 0x7E00 (512 byte bootloader)
0x3E00 -> 0x7C00 (1024 byte bootloader)
0x3C00 -> 0x7800 (2048 byte bootloader)
0x3800 -> 0x7000 (4096 byte bootloader)

 There are two bytes per word, so multiply the word addresses by 2 to get the byte address.

**Comment by nickgammon** [comment]
This is resolved, then? Yes, the figures in the datasheet mention words (2 bytes) at a time, and bytes at other times.
