### ISSUE TITLE
is:issue is:open Modifying original sketch

### ISSUE THREAD

**Issue by vsavic** [nickgammon/arduino_sketches#55]
Would it be OK to change this section after modifying original sketch and adding some additional functionality in order to avoid possible wiring confusion because of slightly different board before publishing my modifications?

So, in this section, from this:

> /*
 For more details, photos, wiring, instructions, see:
    http://www.gammon.com.au/forum/?id=11638
...
 Copyright 2012 Nick Gammon. 
   */

To: 
> // Original Author: Nick Gammon
    // Modified by ...
    /*
    For original project idea, details, photos, wiring, instructions, see:
        http://www.gammon.com.au/forum/?id=11638
    Copyright 2012 Nick Gammon.
     ...
   */

**Comment by nickgammon** [comment]
Yes, I don't see any problem with that. The license which is part of the files states that you can modify and distribute the code, providing you retain the copyright notice. You can certainly state that you made improvements to it.

**Comment by vsavic** [comment]
Thanks Nick, that's what I thought, but just wanted to make sure.
