### ISSUE TITLE
board programmer timeout

### ISSUE THREAD

**Issue by NicoHood** [nickgammon/arduino_sketches#6]
Hi there.
Here is a suggestion for a timeout if you want to read a new avr. I just dont know how to post pull requests. Feel free to add it. The link might be dead in one week when I will merge it to the master.

https://github.com/NicoHood/HoodLoader2/commit/db6ee43162eb907d33e9106ce682bb6e60a6748a#diff-860d57f25358bdf413c9c5f1448abecbR629

**Comment by nickgammon** [comment]
Added your code in a modified form.

https://github.com/nickgammon/arduino_sketches/commit/cf5518236a849d81925b040dce5658b0400c6469

**Comment by NicoHood** [comment]
looks good :)
