### ISSUE TITLE
Can we program 8051 based MCU with these? 

### ISSUE THREAD

**Issue by HTerminal** [nickgammon/arduino_sketches#67]
Hello @nickgammon  Sir

Can we use these codes to program 8051 based microcontrollers too?

**Comment by nickgammon** [comment]
No.

**Comment by kapil-iitk** [comment]
Probably Yes, you can program 8051 microcontroller (if they support SPI programming such as at89s52) by adopting following 2 changes,

1. Add the signature of the microcontroller 
2. By inverting the reset line (see the data sheet of 8051 microcontroller)

(Looking forward to Nick Gammon for the suggestion)
