### ISSUE TITLE
Programming multiple devices

### ISSUE THREAD

**Issue by gcormier** [nickgammon/arduino_sketches#81]
Hey Nick - I'm not sure if this is the best way to contact you or not, if there is a better way please let me know.

I stumbled on this http://www.gammon.com.au/uploader and was delighted.

My goal is a standalone device that can flash connected devices sequentially, since it takes time to load the boards in each bed of nails, one can be programming while the next is being inserted/removed. My initial guess is for it to have 3 "bays", although 2 might suffice. I also have some constraints by the current chip shortage :)

That said, is it necessary to use a hardware SPI port on the host to flash the target device? Or can we use any pin and bit-bang it, and is that covered in your code?

My currently draft is an ATMEGA328PB. SPI0 is used for the MicroSD card. SPI1 to program a target. However, the issue is that since they share that bus, with separate pins for RESET, once programmed a device may start to drive the bus. Therefore, a suggestion was made to use different pins for each device.

The schematic with the potential issue is below.

Thanks,
Greg

![image](https://user-images.githubusercontent.com/8388983/152035362-ebd2eb09-77b7-4501-8b49-19727e25c01c.png)

**Comment by nickgammon** [comment]
You can bit-bang the target device, in fact the code uses hardware SPI to read the SD card, not to program the target.
