### ISSUE TITLE
Atmega_Hex_Uploader filenames

### ISSUE THREAD

**Issue by SchneHa** [nickgammon/arduino_sketches#82]
Hello Nick,
if uploading files with Windows 10 to MicroSD card, filenames could be named in different ways: Test1.hex, test2.HEX, TEST3.hex, TEST4.HEX ... Unfortunately it seems not possible, to rename filename extensions like .hex to upper case extensions in Windows 10.
The sketch only displays filenames with .HEX (uppercase) no other. Thus, if you know the filenames of the other files they can be choosen and flashed.
It would be easier to use if you convert ALL filenames to upper case filenames and handle it. Maybe it isn't so much effort to change the sketch.
Best regards,
Hans

**Comment by harryberlin** [comment]
in Windows you have to rename in steps before you would swap to upper case.
XYZ.hex -> XYZ.he -> XYZ.HEX

**Comment by SchneHa** [comment]
Thank you for this hint but it would be easier if the sketch would recognize all filenames no matter if they're lower or upper case.

**Comment by nickgammon** [comment]
You can change the sketch yourself to do this.
